### ISSUE TITLE
Reload missing after some config changes.

### ISSUE THREAD

**Issue by ubellavance** [zend-patterns/ZendServerPuppet#43]
When a vhost is added/deleted, make sure httpd is reloaded. Using the API, it seems that the call is `zs-client.sh restartPhp --target=localadmin`. Or a `service httpd reload` may be OK? @mkherlakian?

**Comment by mkherlakian** [comment]
the preferred way is zs-client.sh restartPhp as that only restart the services requiring a restart. Thanks @ubellavance!

**Comment by ubellavance** [comment]
@mkherlakian Does it need to be done after an application action (define, deploy, etc)?

**Comment by ubellavance** [comment]
Fixed in #50 or #55, closing.
