### ISSUE TITLE
Actions don't support capital (uppercase) letters in name

### ISSUE THREAD

**Issue by ubellavance** [zend-patterns/ZendServerPuppet#48]
application and vhost defines don't work when the name contains a capital letter. Well, it works, but the getvar that gets the name of the already-defined objects (app or vhost) doesn't trap it, so puppet tries to create the objects every time, which throws an error because it already exists.  Workaround is to use simple names that are all lowercase.

**Comment by ubellavance** [comment]
@mkherlakian did you experience this problem with the chef cookbook?

**Comment by mkherlakian** [comment]
hmm doesn't ring a bell, but does seem to be more Zend Server related than config provisioning related. I'll investigate and open up a bug as needed.

**Comment by ubellavance** [comment]
When I tried with all caps, it worked, si it's a bit weird.

**Comment by ubellavance** [comment]
Fixed in #50.  It is because puppet facts are always sent to the system in lowercase.
