### ISSUE TITLE
redhat-lsb

### ISSUE THREAD

**Issue by ubellavance** [zend-patterns/ZendServerPuppet#7]
- Is it possible to disable the redhat-lsb check?  We already install redhat-lsb in our basic server configuration
- Is is really necessary to install all the packages requrired by redhat-lsb?  Wouldn't redhat-lsb-core be enough?

Thanks,

**Comment by mkherlakian** [comment]
@ubellavance Sorry for the delay. Actually I think we can. We don't use it with our Chef cookbook and it seems to work fine. Our standard installer script falls back to detecting it another way if detection through lsb_release fails

I'll look into it.
Thanks!

**Comment by ubellavance** [comment]
This issue can be closed as #15 fixes it. Thanks,

**Comment by ubellavance** [comment]
I think I closed the issue too fast.  #15 changes the name of the package, which is good because redhat-lsb installs a lot of unneeded packages, but it doesn't change the fact that I use redhat-lsb-core in my base profile. I'll try to submit a PR that would add a condition based on a new a variable named something like "lsb_package_install" that would be set to true by default. BTW #15 broke RHEL5 compatibility (redhat-lsb-core doesn't exist on RHEL5), but apparently, no one noticed.
